### ISSUE TITLE
WpImportedObject Needs to be more unique

### ISSUE THREAD

**Issue by micmania1** [cam-findlay/wordpressimport-redux#6]
If you try to import multiple XML files you may get duplicate IDs which prevents new posts being imported.

Proposed fix: 
Create a hash of the XML file, and append the post ID: d0be2dc421be4fcd0172e5afceea3970e2f3d940-ID

Another potential fix could be that we use the guid field of each post.

**Comment by camfindlay** [comment]
Migrating this repo to https://github.com/camfindlay/silverstripe-wordpressimport
